name: maven CI

on:
  push:
    branches:
      - master
      - develop
      - 'feat/**'
    paths:
      - 'tonka-bean/pom.xml'
      - 'tonka-bean/src/**'
      - '.github/workflows/tonka-java-7.yml'

  pull_request:
    branches:
      - master
      - develop
      - 'feat/**'
    paths:
      - 'tonka-bean/pom.xml'
      - 'tonka-bean/src/**'
      - '.github/workflows/tonka-java-7.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: ${{ github.event.repository.name }}
      uses: actions/checkout@v4

    - name: Prepare pom.xml
      working-directory: ./tonka-bean
      run: bash patch-jdk7.sh

    - name: Pull legacy maven container
      run: docker pull maven:3.6.1-jdk-7-slim

    - name: Build tonka bean in container
      working-directory: ./tonka-bean
      run: docker run --rm --name tonka-java-7 -v "$(pwd)":/app -w /app maven:3.6.1-jdk-7-slim mvn clean package

    - name: Archive generated JAR file
      uses: actions/upload-artifact@v4
      with:
        name: tonka-bean-java-7
        path: tonka-bean/target/*.jar
